config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root 'recipe#index'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  resources :users, only: [:index, :show] do
    resources :recipe, only: [:index, :new, :show, :create, :destroy]
    resources :inventories, controller: 'inventory', only: [:index, :show, :new, :create, :destroy] do
      resources :foods, only: [:index, :show, :new, :create, :destroy] do
        resources :inventory_food, only: [:new, :create, :destroy]
      end
    end
  end

  resources :inventory_food, only: [:new, :create, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
  end
  post 'inventory_foods/:id/create', to: 'inventory_food#create'
  get 'inventory_food/:id/new', to: 'inventory_food#new'

  resources :shopping_list, only: [:new, :index, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
    delete 'shopping_list/:recipe_id', to: 'shopping_lists#destroy'
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]

  patch '/recipe/:id', to: 'recipe#toggle_public', as: :update_recipe




  resources :recipe, only: [:index, :show, :destroy] do
    resources :recipe_food, only: [:create, :new, :edit, :update, :destroy]
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  has_many :inventory_foods, dependent: :delete_all
  has_many :inventories, through: :inventory_foods, dependent: :destroy
  has_many :recipe_foods, dependent: :delete_all
  has_many :recipes, through: :recipe_foods

  validates :measurement_unit, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.includes(:user).all
  end

  def show
    @food = current_user.foods.includes(:user).find(params[:id])
    @inventories = Inventory.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      flash[:success] = 'New Food has been created !!'
      redirect_to foods_path
    else
      flash['alert'] = 'Food could not created !!'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:success] = 'Food has been deleted successfully'
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<div class="container h-screen px-0">
  <div class="container w-full flex justify-between items-center mt-8 mb-4 p-0">
    <h2 class="text-grayDark">List of foods</h2>
  </div>
  <table class="table table-hover">
    <thead class="table-dark text-xs md:text-md lg:text-lg">
      <tr class="font-thin text-center">
        <th scope="col">Food</th>
        <th scope="col">Unit</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr class="text-xs md:text-md lg:text-lg text-center even:bg-slate-200 odd:bg-slate-300">
          <th scope="row"><%= food.name %></th>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <td><%= button_to "Delete", food_path(food.id), method: :delete, class: "text-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="container-fluid mt-2 md:mt-4 bg-primary flex justify-center">
    <%= link_to "Add food", new_food_path , class:"w-full fixed bottom-0 z-20 text-white bg-primary text-center py-2 md:py-3 text-decoration-none" %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container b-2 mt-8">
    <h2 class="text mb-4 md:mb-12 lg:mb-8">Add new food</h2>
  <%= form_with model: @food, url: foods_path,  local: true, data: {turbo:false} do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "w-full border focus:border-transparent focus:ring-1 rounded" %>
    </div>
    <div class="mb-3">
      <%= f.label :measurement_unit, class: "form-label" %>
      <%= f.number_field :measurement_unit, class: "w-full border focus:border-transparent focus:ring-1 rounded" %>
    </div>
    <div class="mb-3">
      <%= f.label :price, class: "form-label" %>
      <%= f.number_field :price, class: "w-full border focus:border-transparent focus:ring-1 rounded" %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>