config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root 'recipe#index'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  resources :users, only: [:index, :show] do
    resources :recipe, only: [:index, :new, :show, :create, :destroy]
    resources :inventories, controller: 'inventory', only: [:index, :show, :new, :create, :destroy] do
      resources :foods, only: [:index, :show, :new, :create, :destroy] do
        resources :inventory_food, only: [:new, :create, :destroy]
      end
    end
  end

  resources :inventory_food, only: [:new, :create, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
  end
  post 'inventory_foods/:id/create', to: 'inventory_food#create'
  get 'inventory_food/:id/new', to: 'inventory_food#new'

  resources :shopping_list, only: [:new, :index, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
    delete 'shopping_list/:recipe_id', to: 'shopping_lists#destroy'
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]

  patch '/recipe/:id', to: 'recipe#toggle_public', as: :update_recipe




  resources :recipe, only: [:index, :show, :destroy] do
    resources :recipe_food, only: [:create, :new, :edit, :update, :destroy]
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  has_many :inventory_foods, dependent: :delete_all
  has_many :foods, through: :inventory_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def index
    @inventories = current_user.inventories.includes(:user).all
  end

  def show
    @inventory = current_user.inventories.includes(:user).find(params[:id])
    @inventory_food = @inventory.inventory_foods.includes(:food)
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user = current_user
    if @inventory.save
      flash[:success] = 'New inventory has been created !!'
      redirect_to user_inventories_path
    else
      flash['alert'] = 'Inventory could not created !!'
      render :new
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    flash[:success] = 'Inventory has been deleted successfully'
    redirect_to user_inventories_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventory/index.html.erb
<div class = 'container px-0 d-flex flex-column mb-2 justify-around gap-3'>
  <% if @inventories.empty? %>
    <h2 class="mt-4 text-center"><em>There are no Inventories yet !!</em></h2>
  <% else %>
    <% @inventories.each do |inventory| %>
      <div class='container p-2 flex flex-col gap-3 rounded border border-grayLight'>
        <%= link_to inventory.name, user_inventory_path(id: inventory), class:'text-uppercase'%>
        <div class=''>
          <p>
            <%= inventory.description %>
          </p>
        </div>
        <%= button_to 'REMOVE', user_inventory_path(id: inventory), method: :delete, class:'text-danger'%>
      </div>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to new_user_inventory_path do %>
      <div class="container px-0 flex justify-center md:justify-start items-center md:items-start">
        <span class="btn btn-primary bg-primary">New Inventory</span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/inventory/new.html.erb
<div class="container px-0">
  <%= form_with model: Inventory, url: user_inventories_path, method: :post do |f| %>

  <% if @inventory.errors.any? %>
     <ul class = "errors-decr">
        <% @inventory.errors.full_messages.each do |errors| %>
          <li><%= errors %></li>
        <% end %>
     </ul>
  <% end %>
  <%= f.text_field :name, placeholder:"Inventory name", class:"w-full border focus:border-transparent focus:ring-1 rounded"  %>
  <%= f.text_area :description, placeholder:"Inventory description", class:"w-full border focus:border-transparent focus:ring-1 mt-3 rounded" %>
  <%= f.submit "Create Inventory", class: "btn btn-success mt-4" %>
<% end %>
</div>

app/views/inventory/show.html.erb
<section class = 'container px-0 flex flex-column mb-2 align-items-center pt-8'>
  <div class="container px-0 flex flex-col md:felx-row  gap-4">
    <span class="text-uppercase font-bold md:text-center md:text-xl lg:text-2xl"><%= @inventory.name %></span>
    <%= link_to "/inventory_food/#{@inventory.id}/new", method: :post do %>
      <div class="container px-0 flex md:justify-end">
        <span class="text-uppercase text-sm md:text-xl btn btn-primary">Add Food</span>
      </div>
    <% end %>
  </div>
  <hr>
  <div class="container px-0">
    <table class = "w-full table table-hover mb-2 items-center" >
      <thead class="bg-black text-grayLight text-sm md:text-xl lg:text-xl font-extralight">
        <tr class="md:text-center">
          <th>Food</th>
          <th>Pounds</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="text-sm md:text-lg">
        <% @inventory_food.each do |f| %>
          <tr class="odd:bg-slate-200 even:bg-slate-300 text-sm md:text-lg lg:text-xl md:text-center">
          <td><%= f.food.name %></td>
          <td><%= f.quantity %> Lbs</td>
          <td><%= button_to 'Delete', "/users/#{current_user.id}/inventories/#{@inventory.id}/foods/#{f.food.id}/inventory_food/#{f.id}", method: :delete, class: "text-danger" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</section>