config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root 'recipe#index'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  resources :users, only: [:index, :show] do
    resources :recipe, only: [:index, :new, :show, :create, :destroy]
    resources :inventories, controller: 'inventory', only: [:index, :show, :new, :create, :destroy] do
      resources :foods, only: [:index, :show, :new, :create, :destroy] do
        resources :inventory_food, only: [:new, :create, :destroy]
      end
    end
  end

  resources :inventory_food, only: [:new, :create, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
  end
  post 'inventory_foods/:id/create', to: 'inventory_food#create'
  get 'inventory_food/:id/new', to: 'inventory_food#new'

  resources :shopping_list, only: [:new, :index, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
    delete 'shopping_list/:recipe_id', to: 'shopping_lists#destroy'
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]

  patch '/recipe/:id', to: 'recipe#toggle_public', as: :update_recipe




  resources :recipe, only: [:index, :show, :destroy] do
    resources :recipe_food, only: [:create, :new, :edit, :update, :destroy]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :destroy
  has_many :foods, through: :recipe_food

  validates :name, :description, :cooking_time, :preparation_time, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def load_and_authorize_resource
    @recipe = Recipe.find(params[:id])
    authorize! :manage, @recipe
  end

  def index
    @recipes = current_user.recipes.includes(:user, :recipe_foods).order(created_at: :desc)
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @shopping_list = Food.all
  end

  def new
    @recipe = Recipe.new
    @params = params
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to user_recipe_index_path
    else
      flash['alert'] = 'There was an error in adding recipe item'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    if @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully!'
      redirect_to user_recipe_path(current_user)
    elsif @recipe.errors.any?
      flash[:alert] = 'There was an error in deleting recipe item'
      render :show
    end
  end

  def toggle_public
    @recipe = set_recipe
    @recipe.public = !@recipe.public
    text = 'private'
    text = 'public' if @recipe.public
    if @recipe.save
      flash[:success] = "#{@recipe.name} is now #{text}!"
    else
      flash[:fail] = @recipe.public
    end
    redirect_to recipe_path(@recipe.id)
  end

  def public_recipes
    @recipes = Recipe.where(public: true)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/recipe/_recipe.html.erb
<% @recipes.includes([:user]).each do |recipe| %>
  <div id="container-card" class="container w-full md:w-3/4 lg:w-9/12 h-auto flex flex-col pt-2 px-0  pb-2 mb-4 md:mb-6 sm:py-12 m-0 justify-center items-start border rounded">
    <div class="w-full flex justify-between items-center px-2">
      <span class="text-sm md:text-lg lg:text-2xl">Recipe No: <%= recipe.id%></span>
      <span>
        <% if recipe.public %>
          <span class="badge bg-primary">Public</span>
        <% else %>
          <span class="badge bg-secondary">Private</span>
        <% end %>
      </span>
    </div>
    <%= link_to(recipe_path(recipe.id)) do %>
      <div class="w-full border-b p-2 border-grayLight sm:shadow-md shadow-md flex justify-between sm:flex-row space-x-2">
        <div class="flex flex-col gap-2">
          <span class="text-grayDark text-md md:text-lg lg:text-2xl text-decoration-none font-semibold"><%= recipe.name %></span>
          <span class="text-grayDark"><i class="text-decoration-none text-xs md:text-lg"><%= recipe.user.name %></i></span>
        </div>
      </div>
      <span class="list-group list-group-flush w-full">
        <p class="list-group-item text-sm md:text-lg"><%= recipe.description %></p>
      </span>
    <% end %>
    <div class="container mt-2 md:mt-4 flex justify-end items-end">
      <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: "btn text-danger" %>
    </div>
  </div>
<% end %>

app/views/recipe/delete.html.erb
<div class="recipe-info">
      <p><%= link_to "Back To Recipes List", recipe_path %></p>
      <h2>Delete Recipe</h2>
</div>

<div class="recipe-form">
      <%= form_for(@recipe, :method => 'delete') do |f| %>
        <p>Are you sure you want to delete the <strong><%= @recipe.name %></strong> recipe?</p>
        <%= f.submit('Delete Recipe') %>
      <% end %>
</div

app/views/recipe/edit.html.erb
# <h1>Editing recipe</h1>

# <%= render "form", recipe: @recipe %>

# <br>

# <div>
#   <%= link_to "Show this recipe", @recipe %> |
#   <%= link_to "Back to recipes", recipe_path %>
# </div>

app/views/recipe/index.html.erb
<div class="w-full md:w-6/12 m-auto h-auto flex flex-col pt-0 py-12 md:py-0 lg:py-0 justify-center align-items-center relative">
  <div class="container p-0">
    <% if @recipes.empty? %>
      <h2 class="text-center">You don't have any recipes yet!</h2>
    <% else %>
      <%= render 'recipe/recipe' %>
    <% end %>
  </div>
</div>
<div class="container-fluid mt-2 md:mt-4 bg-primary flex justify-center">
  <% if user_signed_in? %>
    <%= link_to "New Recipe", new_user_recipe_path(user_id: current_user), class: "w-full fixed bottom-0 z-20 text-white bg-primary text-center py-2 md:py-3 text-decoration-none" %>
  <% end %>
</div>

app/views/recipe/new.html.erb
<%= form_with model: @recipe, url: user_recipe_index_path, local: true, data: {turbo:false} do |f| %>
  <div class="card-body  p-0 sm:p-4 md:p-6 flex flex-col justify-center w-full sm:w-3/4 md:w-6/12 h-auto ml-auto mr-auto mt-2 sm:mt-6 sm:m-auto md:m-auto">
    <h2 class="text-md md:text-xl lg:text-3xl font-bold mb-4"> Add a new recipe </h2>
    <% if @recipe.errors.any? %>
      <div id="error_explanation">
        <p class="text-danger">All fields are required</p>
      </div>
    <% end %>
    <span class="flex flex-col gap-3 mt-2">
      <%= f.text_field :name, placeholder:"Recipe name", class:"w-full border focus:border-transparent focus:ring-1 rounded"  %>
      <%= f.text_field :preparation_time, placeholder:"Preparation time", class:"w-full border focus:border-transparent focus:ring-1 rounded" %>
      <%= f.text_field :cooking_time, placeholder:"Cooking time", class:"w-full border focus:border-transparent focus:ring-1 rounded" %>
      <%= f.text_area :description, placeholder:"Description...", rows: "5", class: "block p-2 w-full border focus:border-transparent focus:ring-1 rounded" %>
    </span>
    <span class="flex gap-2 mt-2 sm:mt-4 md:mt-6 align-items-center text-primary"><%= f.check_box :public, {}, "true", "false"  %> Make this recipe public</span>
    <%= f.submit "Save Recipe", class: "btn btn-success p-2 mt-2 mb-4" %>
  </div>
<% end %>

app/views/recipe/show.html.erb
<div class="mb-4 md:mb-6 flex justify-center items-center gap-2">
  <span class="text-center text-xl md:text-3xl lg:text-4xl"><%=  @recipe.name %></span>
  <% if @recipe.public %>
    <span class="badge bg-primary text-white w-auto p-2 sm:p-2.5 md:p-4 text-md md:text-xl font-medium">Public</span>
  <% else %>
    <span class="badge bg-greenDark text-white w-auto p-2 sm:p-2.5 md:p-4 text-md md:text-xl font-medium">Private</span>
  <% end %>
</div>
<div class="container w-full p-0 border rounded">
  <div class="w-full md:mt-4 p-2 align-items-center">
    <%= button_to 'update', update_recipe_path(id: @recipe), method: :patch, class: "btn btn-primary btn-sm" %>
  </div>
  <div class="w-full px-2 border-b border-grayLight">
    <h4 class="fw-normal my-1 text-sm sm:text:md md:text-xl text-grayDark">Preparation Time:
      <% if @recipe.preparation_time/60 && @recipe.preparation_time%60 > 1 %>
        <%= @recipe.preparation_time/60 %>hrs :
        <%= @recipe.preparation_time%60 %>mins
      <% else %>
        <%= @recipe.preparation_time/60 %>hr :
        <%= @recipe.preparation_time%60 %>min
      <% end %>
    </h4>
    <h4 class="fw-normal my-1 text-sm sm:text:md md:text-xl text-grayDark">Cooking Time:
      <% if @recipe.cooking_time/60 && @recipe.cooking_time%60 > 1 %>
        <%= @recipe.cooking_time/60 %>hrs :
        <%= @recipe.cooking_time%60 %>mins
      <% else %>
        <span class="text-black">
          <%= @recipe.cooking_time/60 %>hr :
          <%= @recipe.cooking_time%60 %>min
        </span>
      <% end %>
    </h4>
  </div>
  <div class="row card-body px-2">
    <div class="card-body col col-md-12 py-2">
      <h4 class="fw-bold my-0">Description</h4>
      <p class="fs-6 mt-2"><%= @recipe.description %></p>
    </div>
  </div>
</div>
<div class="container mt-5 px-0 flex flex-col md:flex-row justify-center md:justify-between content">
  <div class='w-auto flex md:flex-col items-center px-0 gap-2 mb-4'>
    <button type="button" class="btn btn-primary w-full text-xs md:text-lg p-2 md:py-4 text-white md:text-md bg-primary" data-bs-toggle="modal" data-bs-target="#recipeModal">
      Generate shopping list
    </button>
    <%= link_to new_recipe_recipe_food_path(@recipe.id), class: "btn btn-border w-full text-xs md:text-lg text-center py-2 md:py-4 px-4 text-primary border border-grayDark text-decoration-none" do %>
      <span>Add Ingredients</span>
    <% end %>
  </div>
  <span class="bar w-4"></span>
  <div class="w-full flex justify-center gap-0 md:gap-8">
    <div class="modal fade" id="recipeModal" tabindex="-1" aria-labelledby="recipeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="recipeModalLabel">Generating shopping list</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <%= form_with url: "/inventory_food/#{:inventory_food_id}/shopping_list/#{:recipe_id}", method: :post do |form| %>
            <div class="modal-body">
              Choose an inventory to use:
              <%= form.select :inventory_id, current_user.inventories.order(:name).pluck(:name, :id), {}, class: "mt-3 w-full border focus:border-transparent focus:ring-1 rounded" %>
            </div>
            <div class="modal-footer">
              <%= form.submit 'Generate', class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <table class="w-full mb-4 table table-hover">
      <thead class="bg-black text-grayLight text-sm md:text-xl lg:text-xl font-extralight">
        <tr class>
          <th>Food</th><br/>
          <br/>
          <th>Quantity</th>
          <br/>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <% @shopping_list.each do |food_item| %>
        <tr class="text-start text-sm md:text-lg lg:text-xl odd:bg-slate-200 even:bg-slate-300">
          <td><%= food_item.name %></td>
          <td><%= food_item.price/2 %> g</td>
          <td>$<%= food_item.price %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>