config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root 'recipe#index'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  resources :users, only: [:index, :show] do
    resources :recipe, only: [:index, :new, :show, :create, :destroy]
    resources :inventories, controller: 'inventory', only: [:index, :show, :new, :create, :destroy] do
      resources :foods, only: [:index, :show, :new, :create, :destroy] do
        resources :inventory_food, only: [:new, :create, :destroy]
      end
    end
  end

  resources :inventory_food, only: [:new, :create, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
  end
  post 'inventory_foods/:id/create', to: 'inventory_food#create'
  get 'inventory_food/:id/new', to: 'inventory_food#new'

  resources :shopping_list, only: [:new, :index, :destroy] do
    post 'shopping_list/:recipe_id', to: 'shopping_lists#generate'
    delete 'shopping_list/:recipe_id', to: 'shopping_lists#destroy'
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]

  patch '/recipe/:id', to: 'recipe#toggle_public', as: :update_recipe




  resources :recipe, only: [:index, :show, :destroy] do
    resources :recipe_food, only: [:create, :new, :edit, :update, :destroy]
  end
end

app/models/ability.rb
class Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  has_many :inventory_foods, dependent: :delete_all
  has_many :inventories, through: :inventory_foods, dependent: :destroy
  has_many :recipe_foods, dependent: :delete_all
  has_many :recipes, through: :recipe_foods

  validates :measurement_unit, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  has_many :inventory_foods, dependent: :delete_all
  has_many :foods, through: :inventory_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :inventory, class_name: 'Inventory', foreign_key: 'inventory_id'

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :destroy
  has_many :foods, through: :recipe_food

  validates :name, :description, :cooking_time, :preparation_time, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  validates :quantity, presence: true, numericality: { great_than_or_eaqual_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :delete_all
  has_many :foods, dependent: :delete_all
  has_many :inventories, dependent: :delete_all

  validates :name, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.includes(:user).all
  end

  def show
    @food = current_user.foods.includes(:user).find(params[:id])
    @inventories = Inventory.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      flash[:success] = 'New Food has been created !!'
      redirect_to foods_path
    else
      flash['alert'] = 'Food could not created !!'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:success] = 'Food has been deleted successfully'
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def load_and_authorize_resource
    @recipe = Recipe.find(params[:id])
    authorize! :manage, @recipe
  end

  def index
    @recipes = current_user.recipes.includes(:user, :recipe_foods).order(created_at: :desc)
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @shopping_list = Food.all
  end

  def new
    @recipe = Recipe.new
    @params = params
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to user_recipe_index_path
    else
      flash['alert'] = 'There was an error in adding recipe item'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    if @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully!'
      redirect_to user_recipe_path(current_user)
    elsif @recipe.errors.any?
      flash[:alert] = 'There was an error in deleting recipe item'
      render :show
    end
  end

  def toggle_public
    @recipe = set_recipe
    @recipe.public = !@recipe.public
    text = 'private'
    text = 'public' if @recipe.public
    if @recipe.save
      flash[:success] = "#{@recipe.name} is now #{text}!"
    else
      flash[:fail] = @recipe.public
    end
    redirect_to recipe_path(@recipe.id)
  end

  def public_recipes
    @recipes = Recipe.where(public: true)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    if request.path == path
      'active'
    else
      ''
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventory_food_helper.rb
module InventoryFoodHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_message.html.erb
<div class="notice container sm:w-2/4 md:w-9/12 flex justify-center md:justify-start align-items-center mt-4 sm:mt-6 mb-0">
  <p class="notice text-greenDark text-center"><%= notice %></p>
  <p class="notice text-primary text-center"><%= alert %></p>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="bg-dark px-0 sm:px-4 py-2 md:py-0 sm:py-0 sticky w-full flex justify-center z-20 top-0 left-0">
    <div class="container px-2 flex flex-wrap items-center justify-between mx-auto">
      <span class="flex align-items-center">
        <%= link_to root_path, class: "flex align-items-center" do %>
          <svg aria-hidden="true" class="w-8 h-8 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            fill="white" viewBox="0 0 196.979 196.979" xmlns="http://www.w3.org/2000/svg">
            <path d="M43.48,0C28.1,0.003,15.588,12.517,15.588,27.896v141.188c0,15.38,12.512,27.894,27.893,27.896h131.66
              c3.452,0,6.25-2.798,6.25-6.25v-21.646v-21.646V49.542V6.25c0-3.452-2.798-6.25-6.25-6.25H43.48z M43.481,12.5h125.41v37.042
              v91.645H43.48c-5.687,0.001-10.978,1.716-15.392,4.649V27.896C28.088,19.408,34.994,12.501,43.481,12.5z M168.891,184.479H43.482
              c-8.488-0.001-15.394-6.908-15.394-15.396c0-8.488,6.905-15.395,15.393-15.396h125.41v9.146h-98.41c-3.452,0-6.25,2.798-6.25,6.25
              c0,3.452,2.798,6.25,6.25,6.25h98.41V184.479z"/>
            <path d="M73.496,87.7v23.664c0,3.452,2.798,6.25,6.25,6.25h37.486c3.452,0,6.25-2.798,6.25-6.25V87.701
              c8.258-3.315,13.982-11.413,13.982-20.669c0-11.935-9.437-21.706-21.24-22.244c-4.161-5.506-10.644-8.791-17.734-8.791
              c-7.093,0-13.575,3.285-17.735,8.791c-11.804,0.538-21.241,10.31-21.241,22.244C59.514,76.289,65.239,84.386,73.496,87.7z
              M81.782,57.265c0.473,0,0.954,0.035,1.433,0.105c2.686,0.397,5.313-0.986,6.512-3.418c1.661-3.364,5.02-5.455,8.765-5.455
              c3.744,0,7.103,2.091,8.766,5.457c1.2,2.432,3.839,3.811,6.513,3.416c0.476-0.07,0.956-0.105,1.429-0.105
              c5.386,0,9.768,4.382,9.768,9.768c0,4.905-3.663,9.069-8.52,9.685c-3.122,0.396-5.463,3.053-5.463,6.2v22.196H85.996V83.331
              c0-0.007,0.001-0.015,0.001-0.021c0.207-3.293-2.182-6.18-5.455-6.593c-4.862-0.613-8.528-4.776-8.528-9.685
              C72.014,61.646,76.396,57.265,81.782,57.265z"/>
          </svg>
          <span class="hidden md:flex whitespace-nowrap text-xl px-2 text-decoration-none font-normal text-white">Recipe App</span>
        <% end %>
      </span>
      <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center text-sm text-gray-500 md:hidden focus:outline-none focus:ring-0" aria-controls="navbar-default" aria-expanded="false" id="btn-toggle">
        <span class="sr-only">Open main menu</span>
        <svg class="w-8 h-8" aria-hidden="true" fill="white" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="flex flex-col mt-4 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-md md:font-medium">
          <li class="nav-item">
            <%= link_to 'Foods', foods_path, class: "text-decoration-none block py-2 pr-4 pl-3 text-grayLight rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-gray-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Public recipe', public_recipes_path, class: "whitespace-nowrap text-decoration-none block py-2 pr-4 pl-3 text-grayLight rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-gray-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Inventories', user_inventories_path(user_id: current_user), class: "text-decoration-none block py-2 pr-4 pl-3 text-grayLight rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-gray-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li class="nav-item">
            <%= link_to 'shopping list', shopping_list_index_path, class: "whitespace-nowrap text-decoration-none block py-2 pr-4 pl-3 text-grayLight rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-gray-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, data: { turbo: false }, class:"btn btn-primary" %>
        </ul>
      <div>
    </diV>
  </nav>
<% end %>
<%= javascript_include_tag "application", async: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>
  <% if user_signed_in? %>
    <body class="bg-#F1F1F6">
      <%= render 'layouts/navbar' %>
      <main class="root container-fluid h-auto">
        <%= render 'layouts/message' %>
        <%= yield %>
      </main>
    </body>
    <% else %>
    <body class="bg-cover bg-fixed" background="https://images.unsplash.com/photo-1495546968767-f0573cca821e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1631&q=80">
      <main class="root container-fluid h-auto">
        <%= render 'layouts/message' %>
        <%= yield %>
      </main>
    </body>
  <% end %>
</html>